### ISSUE TITLE
Feature - Add login functionality to our Chirp! application.

### ISSUE THREAD

**Issue by AndreasBC99** [ITU-BDSA23-GROUP11/Chirp#126]
As a user, I want security of my personal information and trust the publisher of a website that I use. I.e. we need to implement an authentication platform that is trusted and consistent to our project.

**The following options needs to be discussed and implemented together as a group**
- _Individual Accounts:_ 
https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/other-logins?view=aspnetcore-7.0

- _Microsoft Identity Platform:_
https://learn.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-github?pivots=b2c-user-flow

- _Azure Web Apps Easy Auth:_
https://learn.microsoft.com/en-us/azure/app-service/overview-authentication-authorization

**Acceptance Criteria**
- [x] A user is able to login
- [x] A user is able to logout
- [x] The platform is easy for an user to use
- [x] The platform is secure
- [x] Everyone in the group needs to understand the implementation
- [x] Everyone in the group has agreed on a platform
- [x] Everyone in the group is a part of the implementation

**Comment by AndreasBC99** [comment]
Update: Together in the group, we have decided to use Microsoft Identity Platform.
