### ISSUE TITLE
Git - Improve Git workflows CI/CD

### ISSUE THREAD

**Issue by marcusaandahl** [ITU-BDSA23-GROUP11/Chirp#26]
We should add the follow git workflows:
![Image](https://github.com/ITU-BDSA23-GROUP11/Chirp/assets/55247594/fc284a6f-4a1c-4526-8e77-892a3b351cf0)

This is from [the official .NET and Github actions documentation](https://learn.microsoft.com/en-us/dotnet/devops/github-actions-overview) and should probably be respected.
We currently have parts of all 4 workflows in 1, and should probably split it up.
The workflows are mildly linked to the issues #23 and #25, and we can split this up as an epic issue, with 4 sub-issues (for each workflow.)

The workflows are:
- [x] **Build and validation** (see if code builds and compiles at all) - already implemented and should just be renamed.
- [x] **Build and test** (runs unit tests) - already implemented in current workflow, and should just be split up in its own.
- [x] **Publish App** (packages and publishes source code) - see issue #25.
- [x] **Code QA and Analysis** (analyses for security and test vulnerabilities along with coding errors) - see issue #23.
