### ISSUE TITLE
Fix - Improve test coverage

### ISSUE THREAD

**Issue by marcusaandahl** [ITU-BDSA23-GROUP11/Chirp#61]
Currently, we have bad test coverage. We want to fix that, such that we get coverage above our thresholds.
Thereafter, we can re-enable our check to fail if coverage is bad, in order to ensure good test coverage.

Criteria:
- [x] Research mock libraries for testing
- [x] Add tests such that we have adequate coverage - #113 
- [x] Re-enable code coverage workflow check being able to fail
