### ISSUE TITLE
Minor & enhancements v1.0.0

### ISSUE THREAD

**Issue by marcusaandahl** [ITU-BDSA23-GROUP11/Chirp#75]
There are minor bugs, which need fixing:
- [ ] Fix wrong filepath in CsvDatabase - #76
- [ ] Ensure better connection possibilities - #77
- [ ] Better error handling and logging - #79 
- [ ] More generic classes - #80
