### ISSUE TITLE
Refactor - Switch database to file-based SQLite database

### ISSUE THREAD

**Issue by AndreasBC99** [ITU-BDSA23-GROUP11/Chirp#82]
We need to switch database from CSV to SQLite. I.e. the CSV database needs to be retired.

- [ ] Modify the code in CheepService.cs so that it retrieves cheeps and their authors from an SQLite database.
- [ ] Use schema.sql and dump.sql from the lecture
- [ ] Modify the code in the method GetCheeps() in CheepService.cs so that it executes an SQL query against the SQLite database.
